### ISSUE TITLE
random build failure: org.O1.SecurityAccounts.gUserManagement.service

### ISSUE THREAD

**Issue by pohly** [01org/gumd#26]
Occasionally, compiling gumd with a high degree of parallelism fails:

|  /usr/bin/install -c -m 644 ../../../src/daemon/dbus/services/org.O1.SecurityAccounts.gUserManagement.service '/work/build/iot/quark/tmp-glibc/work/i586-iotos-linux/gumd/1.0.8-r0/image/usr/share/dbus-1/system-services'
|  /usr/bin/install -c -m 644 ../../../src/daemon/dbus/services/org.O1.SecurityAccounts.gUserManagement.service '/work/build/iot/quark/tmp-glibc/work/i586-iotos-linux/gumd/1.0.8-r0/image/usr/share/dbus-1/system-services'
| /usr/bin/install: cannot change permissions of '/work/build/iot/quark/tmp-glibc/work/i586-iotos-linux/gumd/1.0.8-r0/image/usr/share/dbus-1/system-services/org.O1.SecurityAccounts.gUserManagement.service': No such file or directory
| Makefile:601: recipe for target 'install-nodist_dbusserviceDATA' failed

Note that there are two invocations of install with identical parameters. This then fails because one instance removes the file that the second one is still working on.

**Comment by izaman** [comment]
Thanks for notifying it. I am trying to reproduce it.. and also will look into it now..

**Comment by pohly** [comment]
Reproducing it might be hard due to the race conditions. Perhaps the file gets added twice to the variable which determines what needs to be installed? Just guessing, though.

**Comment by izaman** [comment]
its really strange.. the recipe is quite simple ..
FILES_${PN} += " ${prefix}/share/dbus-1/system-services/*UserManagement*.service"

and in makefile it looks like below.. any will look into it on monday.. were u able to reproduce on your local machines or somewhere in jenkins you encountered the issue?

if USE_DBUS_SERVICE
dbusservicedir = $(DBUS_SERVICES_DIR)
dbusservice_DATA = \
    $(SERVICES_DIR)/org.O1.SecurityAccounts.gUserManagement.service
nodist_dbusservice_DATA = \
    $(SERVICES_DIR)/org.O1.SecurityAccounts.gUserManagement.service
endif

**Comment by kanavin** [comment]
Why is it listed twice in the Makefile?

**Comment by izaman** [comment]
it is actually dbusservice_DATA and nodist_dbusservice_DATA .. both r different.. second one ensures that make dist does not include the file

**Comment by kanavin** [comment]
Then you only need the second one.

**Comment by izaman** [comment]
aah ok then i can take it out.. @pohly would it be possible that you can try reproducing it once i pushed the fix?

**Comment by pohly** [comment]
I cannot reproduce it reliably either. Push a fix and we'll continue consider it resolved unless it reappears.

**Comment by izaman** [comment]
no the above commit does not fix the issue.. I managed to reproduce it just now..

**Comment by kanavin** [comment]
But why would 'make install'  delete files that it had installed? Even though it's hard to be sure, because autotools-produced makefiles are an impenetrable jungle. 

Does either of you have a full log, so that there is more context, and maybe it's possible to guess where the deletion happens?

**Comment by izaman** [comment]
Log data follows:
| DEBUG: SITE files ['endian-little', 'bit-32', 'ix86-common', 'common-linux', 'common-glibc', 'i586-linux', 'common']
| DEBUG: Executing shell function do_install
| NOTE: make -j 16 DESTDIR=/opt/iotos/tmp-glibc/work/i586-iotos-linux/gumd/1.0.8-r0/image install
| Making install in src
| make[1]: Entering directory `/opt/iotos/tmp-glibc/work/i586-iotos-linux/gumd/1.0.8-r0/build/src'
| Making install in common
| make[2]: Entering directory `/opt/iotos/tmp-glibc/work/i586-iotos-linux/gumd/1.0.8-r0/build/src/common'
| Making install in dbus
| make[3]: Entering directory `/opt/iotos/tmp-glibc/work/i586-iotos-linux/gumd/1.0.8-r0/build/src/common/dbus'
| make  install-am
| make[4]: Entering directory `/opt/iotos/tmp-glibc/work/i586-iotos-linux/gumd/1.0.8-r0/build/src/common/dbus'
| make[5]: Entering directory `/opt/iotos/tmp-glibc/work/i586-iotos-linux/gumd/1.0.8-r0/build/src/common/dbus'
| make[5]: Nothing to be done for `install-exec-am'.
|  /bin/mkdir -p '/opt/iotos/tmp-glibc/work/i586-iotos-linux/gumd/1.0.8-r0/image/usr/share/dbus-1/interfaces'
|  /usr/bin/install -c -m 644 /opt/iotos/tmp-glibc/work/i586-iotos-linux/gumd/1.0.8-r0/git/src/common/dbus/../../../src/common/dbus/interfaces/org.O1.SecurityAccounts.gUserManagement.User.xml /opt/iotos/tmp-glibc/work/i586-iotos-linux/gumd/1.0.8-r0/git/src/common/dbus/../../../src/common/dbus/interfaces/org.O1.SecurityAccounts.gUserManagement.UserService.xml /opt/iotos/tmp-glibc/work/i586-iotos-linux/gumd/1.0.8-r0/git/src/common/dbus/../../../src/common/dbus/interfaces/org.O1.SecurityAccounts.gUserManagement.Group.xml /opt/iotos/tmp-glibc/work/i586-iotos-linux/gumd/1.0.8-r0/git/src/common/dbus/../../../src/common/dbus/interfaces/org.O1.SecurityAccounts.gUserManagement.GroupService.xml '/opt/iotos/tmp-glibc/work/i586-iotos-linux/gumd/1.0.8-r0/image/usr/share/dbus-1/interfaces'
| make[5]: Leaving directory `/opt/iotos/tmp-glibc/work/i586-iotos-linux/gumd/1.0.8-r0/build/src/common/dbus'
| make[4]: Leaving directory `/opt/iotos/tmp-glibc/work/i586-iotos-linux/gumd/1.0.8-r0/build/src/common/dbus'
| make[3]: Leaving directory `/opt/iotos/tmp-glibc/work/i586-iotos-linux/gumd/1.0.8-r0/build/src/common/dbus'
| make[3]: Entering directory `/opt/iotos/tmp-glibc/work/i586-iotos-linux/gumd/1.0.8-r0/build/src/common'
| make[4]: Entering directory `/opt/iotos/tmp-glibc/work/i586-iotos-linux/gumd/1.0.8-r0/build/src/common'
|  /bin/mkdir -p '/opt/iotos/tmp-glibc/work/i586-iotos-linux/gumd/1.0.8-r0/image/usr/lib'
|  /bin/mkdir -p '/opt/iotos/tmp-glibc/work/i586-iotos-linux/gumd/1.0.8-r0/image/usr/include/gum/common'
|  ../../i586-iotos-linux-libtool   --mode=install /usr/bin/install -c   libgum-common.la '/opt/iotos/tmp-glibc/work/i586-iotos-linux/gumd/1.0.8-r0/image/usr/lib'
|  /usr/bin/install -c -m 644 /opt/iotos/tmp-glibc/work/i586-iotos-linux/gumd/1.0.8-r0/git/include/gum/common/gum-config-dbus.h /opt/iotos/tmp-glibc/work/i586-iotos-linux/gumd/1.0.8-r0/git/include/gum/common/gum-config-general.h /opt/iotos/tmp-glibc/work/i586-iotos-linux/gumd/1.0.8-r0/git/include/gum/common/gum-config.h /opt/iotos/tmp-glibc/work/i586-iotos-linux/gumd/1.0.8-r0/git/include/gum/common/gum-dictionary.h /opt/iotos/tmp-glibc/work/i586-iotos-linux/gumd/1.0.8-r0/git/include/gum/common/gum-error.h /opt/iotos/tmp-glibc/work/i586-iotos-linux/gumd/1.0.8-r0/git/include/gum/common/gum-log.h /opt/iotos/tmp-glibc/work/i586-iotos-linux/gumd/1.0.8-r0/git/include/gum/common/gum-disposable.h /opt/iotos/tmp-glibc/work/i586-iotos-linux/gumd/1.0.8-r0/git/include/gum/common/gum-crypt.h /opt/iotos/tmp-glibc/work/i586-iotos-linux/gumd/1.0.8-r0/git/include/gum/common/gum-lock.h /opt/iotos/tmp-glibc/work/i586-iotos-linux/gumd/1.0.8-r0/git/include/gum/common/gum-file.h /opt/iotos/tmp-glibc/work/i586-iotos-linux/gumd/1.0.8-r0/git/include/gum/common/gum-string-utils.h /opt/iotos/tmp-glibc/work/i586-iotos-linux/gumd/1.0.8-r0/git/include/gum/common/gum-utils.h /opt/iotos/tmp-glibc/work/i586-iotos-linux/gumd/1.0.8-r0/git/include/gum/common/gum-validate.h /opt/iotos/tmp-glibc/work/i586-iotos-linux/gumd/1.0.8-r0/git/include/gum/common/gum-user-types.h /opt/iotos/tmp-glibc/work/i586-iotos-linux/gumd/1.0.8-r0/git/include/gum/common/gum-group-types.h '/opt/iotos/tmp-glibc/work/i586-iotos-linux/gumd/1.0.8-r0/image/usr/include/gum/common'
| i586-iotos-linux-libtool: install: /usr/bin/install -c .libs/libgum-common.so.0.0.0 /opt/iotos/tmp-glibc/work/i586-iotos-linux/gumd/1.0.8-r0/image/usr/lib/libgum-common.so.0.0.0
| i586-iotos-linux-libtool: install: (cd /opt/iotos/tmp-glibc/work/i586-iotos-linux/gumd/1.0.8-r0/image/usr/lib && { ln -s -f libgum-common.so.0.0.0 libgum-common.so.0 || { rm -f libgum-common.so.0 && ln -s libgum-common.so.0.0.0 libgum-common.so.0; }; })
| i586-iotos-linux-libtool: install: (cd /opt/iotos/tmp-glibc/work/i586-iotos-linux/gumd/1.0.8-r0/image/usr/lib && { ln -s -f libgum-common.so.0.0.0 libgum-common.so || { rm -f libgum-common.so && ln -s libgum-common.so.0.0.0 libgum-common.so; }; })
| i586-iotos-linux-libtool: install: /usr/bin/install -c .libs/libgum-common.lai /opt/iotos/tmp-glibc/work/i586-iotos-linux/gumd/1.0.8-r0/image/usr/lib/libgum-common.la
| i586-iotos-linux-libtool: warning: remember to run 'i586-iotos-linux-libtool --finish /usr/lib'
| make[4]: Leaving directory `/opt/iotos/tmp-glibc/work/i586-iotos-linux/gumd/1.0.8-r0/build/src/common'
| make[3]: Leaving directory `/opt/iotos/tmp-glibc/work/i586-iotos-linux/gumd/1.0.8-r0/build/src/common'
| make[2]: Leaving directory `/opt/iotos/tmp-glibc/work/i586-iotos-linux/gumd/1.0.8-r0/build/src/common'
| Making install in daemon
| make[2]: Entering directory `/opt/iotos/tmp-glibc/work/i586-iotos-linux/gumd/1.0.8-r0/build/src/daemon'
| Making install in core
| make[3]: Entering directory `/opt/iotos/tmp-glibc/work/i586-iotos-linux/gumd/1.0.8-r0/build/src/daemon/core'
| make[4]: Entering directory `/opt/iotos/tmp-glibc/work/i586-iotos-linux/gumd/1.0.8-r0/build/src/daemon/core'
| make[4]: Nothing to be done for `install-data-am'.
|  /bin/mkdir -p '/opt/iotos/tmp-glibc/work/i586-iotos-linux/gumd/1.0.8-r0/image/usr/lib'
|  ../../../i586-iotos-linux-libtool   --mode=install /usr/bin/install -c   libgumd-core.la '/opt/iotos/tmp-glibc/work/i586-iotos-linux/gumd/1.0.8-r0/image/usr/lib'
| i586-iotos-linux-libtool: install: /usr/bin/install -c .libs/libgumd-core.so.0.0.0 /opt/iotos/tmp-glibc/work/i586-iotos-linux/gumd/1.0.8-r0/image/usr/lib/libgumd-core.so.0.0.0
| i586-iotos-linux-libtool: install: (cd /opt/iotos/tmp-glibc/work/i586-iotos-linux/gumd/1.0.8-r0/image/usr/lib && { ln -s -f libgumd-core.so.0.0.0 libgumd-core.so.0 || { rm -f libgumd-core.so.0 && ln -s libgumd-core.so.0.0.0 libgumd-core.so.0; }; })
| i586-iotos-linux-libtool: install: (cd /opt/iotos/tmp-glibc/work/i586-iotos-linux/gumd/1.0.8-r0/image/usr/lib && { ln -s -f libgumd-core.so.0.0.0 libgumd-core.so || { rm -f libgumd-core.so && ln -s libgumd-core.so.0.0.0 libgumd-core.so; }; })
| i586-iotos-linux-libtool: install: /usr/bin/install -c .libs/libgumd-core.lai /opt/iotos/tmp-glibc/work/i586-iotos-linux/gumd/1.0.8-r0/image/usr/lib/libgumd-core.la
| i586-iotos-linux-libtool: warning: remember to run 'i586-iotos-linux-libtool --finish /usr/lib'
| make[4]: Leaving directory `/opt/iotos/tmp-glibc/work/i586-iotos-linux/gumd/1.0.8-r0/build/src/daemon/core'
| make[3]: Leaving directory `/opt/iotos/tmp-glibc/work/i586-iotos-linux/gumd/1.0.8-r0/build/src/daemon/core'
| Making install in dbus
| make[3]: Entering directory `/opt/iotos/tmp-glibc/work/i586-iotos-linux/gumd/1.0.8-r0/build/src/daemon/dbus'
| make[4]: Entering directory `/opt/iotos/tmp-glibc/work/i586-iotos-linux/gumd/1.0.8-r0/build/src/daemon/dbus'
| make[4]: Nothing to be done for `install-exec-am'.
|  /bin/mkdir -p '/opt/iotos/tmp-glibc/work/i586-iotos-linux/gumd/1.0.8-r0/image/usr/share/dbus-1/system-services'
|  /bin/mkdir -p '/opt/iotos/tmp-glibc/work/i586-iotos-linux/gumd/1.0.8-r0/image/etc/dbus-1/system.d'
|  /bin/mkdir -p '/opt/iotos/tmp-glibc/work/i586-iotos-linux/gumd/1.0.8-r0/image/usr/share/dbus-1/system-services'
|  /usr/bin/install -c -m 644 ../../../src/daemon/dbus/services/org.O1.SecurityAccounts.gUserManagement.service '/opt/iotos/tmp-glibc/work/i586-iotos-linux/gumd/1.0.8-r0/image/usr/share/dbus-1/system-services'
|  /usr/bin/install -c -m 644 ../../../src/daemon/dbus/services/org.O1.SecurityAccounts.gUserManagement.service '/opt/iotos/tmp-glibc/work/i586-iotos-linux/gumd/1.0.8-r0/image/usr/share/dbus-1/system-services'
|  /usr/bin/install -c -m 644 gumd-dbus.conf '/opt/iotos/tmp-glibc/work/i586-iotos-linux/gumd/1.0.8-r0/image/etc/dbus-1/system.d'
| /usr/bin/install: cannot change permissions of '/opt/iotos/tmp-glibc/work/i586-iotos-linux/gumd/1.0.8-r0/image/usr/share/dbus-1/system-services/org.O1.SecurityAccounts.gUserManagement.service': No such file or directory
| make[4]: *** [install-dbusserviceDATA] Error 1
| make[4]: *** Waiting for unfinished jobs....
| make[4]: Leaving directory `/opt/iotos/tmp-glibc/work/i586-iotos-linux/gumd/1.0.8-r0/build/src/daemon/dbus'
| make[3]: *** [install-am] Error 2
| make[3]: Leaving directory `/opt/iotos/tmp-glibc/work/i586-iotos-linux/gumd/1.0.8-r0/build/src/daemon/dbus'
| make[2]: *** [install-recursive] Error 1
| make[2]: Leaving directory `/opt/iotos/tmp-glibc/work/i586-iotos-linux/gumd/1.0.8-r0/build/src/daemon'
| make[1]: *** [install-recursive] Error 1
| make[1]: Leaving directory `/opt/iotos/tmp-glibc/work/i586-iotos-linux/gumd/1.0.8-r0/build/src'
| make: *** [install-recursive] Error 1
| ERROR: oe_runmake failed
| WARNING: exit code 1 from a shell command.
| ERROR: Function failed: do_install (log file is located at /opt/iotos/tmp-glibc/work/i586-iotos-linux/gumd/1.0.8-r0/temp/log.do_install.24063)
ERROR: Task 2 (/home/imran/work/iot/iot-os/meta-user-management/recipes-core/gumd/gumd.bb, do_install) failed with exit code '1'
NOTE: Tasks Summary: Attempted 1068 tasks of which 1061 didn't need to be rerun and 1 failed.
No currently running tasks (1068 of 1074)

Summary: 1 task failed:
  /home/imran/work/iot/iot-os/meta-user-management/recipes-core/gumd/gumd.bb, do_install
Summary: There was 1 ERROR message shown, returning a non-zero exit code.

**Comment by kanavin** [comment]
The above log comes from a version without the fix (the file is installed twice).

**Comment by pohly** [comment]
Adding the file twice to the list of installable files looks like a probable explanation of the problem and is fixed now. Let's assume the problem is gone and reopen if it isn't.
